# Generated by Django 4.2.6 on 2023-10-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteImobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Imoveis',
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
